services:
  db:
    image: postgres:16
    container_name: bigdata_snowflake
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
